name: MERN CI

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # ==== BACKEND ====
      - name: Install Backend Dependencies
        working-directory: backend
        run: npm install

      - name: Fix Jest Permission
        working-directory: backend
        run: chmod +x ./node_modules/.bin/jest

      - name: Run Backend Tests
        working-directory: backend
        run: npm test

      # ==== FRONTEND ====
      - name: Install Frontend Dependencies
        working-directory: frontend
        run: npm install

      - name: Fix React Scripts Permission
        working-directory: frontend
        run: chmod +x ./node_modules/.bin/react-scripts

      - name: Run Frontend Tests
        working-directory: frontend
        run: npm test
